
import "./globals.css";


export const metadata = {
  title: "Note Application",
  description: "Generated by Ujer Shaikh using Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-white'>
        {children}
      </body>
    </html>
  );
}
